//
//  BaseballHackDayStyleKit.h
//  CardGenerator
//
//  Created by  on 3/28/15.
//  Copyright (c) 2015 Think Tank Productions. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BaseballHackDayStyleKit : NSObject

// Drawing Methods
+ (void)drawCardCornerWithFrame: (CGRect)frame;
+ (void)drawTexasRangersWithFrame: (CGRect)frame;
+ (void)drawBostonRedSoxWithFrame: (CGRect)frame;
+ (void)drawTorontoBlueJaysWithFrame: (CGRect)frame;
+ (void)drawLSUWithFrame: (CGRect)frame;

@end